### ISSUE TITLE
Broken under Java 8u60

### ISSUE THREAD

**Issue by notpeter** [embulk/embulk-input-s3#15]
The AWS SDK has a dependency (Joda) which broke under Java 1.8 Update 60.  They've fixed the issue upstream, we just need to bump the compile dependency.
https://github.com/aws/aws-sdk-java/issues/444

The error message looks like:
````
com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: D99D949393A2563E), S3 Extended Request ID:  xyxyxyxyxyxx 
````

**Comment by frsyuki** [comment]
I released embulk-input-s3 v0.2.4 which includes aws-java-sdk-s3 v1.10.33. Thank you for reporting :+1:
