### ISSUE TITLE
proxy support is needed

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-input-s3#47]
Hi
I need to access AWS through a proxy server.
If embulk-input-s3 supports proxy as [embulk-output-s3](https://github.com/llibra/embulk-output-s3) does, it will be very useful.
(If not only host and port but also username and password are supported, it will be more useful.)

Is there any reason not to merge #12 ?

**Comment by muga** [comment]
I merged this feature as https://github.com/embulk/embulk-input-s3/pull/48. I will care of it on next version https://github.com/embulk/embulk-input-s3/issues/49

**Comment by muga** [comment]
I will release v0.2.11 on https://github.com/embulk/embulk-input-s3/pull/50. Please try it.

**Comment by hito4t** [comment]
Thank you!
It works well!
