### ISSUE TITLE
Upgrade aws-java-sdk libraries version for supporting newer region?

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-input-s3#55]
@muga

Just FYI.
I'm wondering whether this plugin (and embulk-input-jdbc) causes similar issue.
https://github.com/embulk/embulk-output-jdbc/pull/166

The current `aws-java-sdk-s3` is `1.10.33`.
https://github.com/embulk/embulk-input-s3/blob/master/build.gradle#L66

**Comment by muga** [comment]
Working on https://github.com/embulk/embulk-input-s3/pull/56

**Comment by hiroyuki-sato** [comment]
Thank you!.
