### ISSUE TITLE
Behavior when there's no target files

### ISSUE THREAD

**Issue by hirosassa** [embulk/embulk-input-s3#82]
Hi, 
I'm now consider about behavior when there's no target files (specified by `path_prefix` or `path`).
I think there is a situation that data loading jobs had better stop when no target files.

In my use case, the input is csv files on S3, and the output is BigQuery table.
When target directory is empty, data loading job generates empty table on BigQuery.
I want to know before it generates such table.

To prevent this, I propose `stop_if_no_target_file: true or false` option.
If you enables this option, data loading job will stop (error) when the situation described above.

How do you think about this option?
(Quick survey on embulk input plugins told me there's no such option on existings)

Thanks,

**Comment by sakama** [comment]
Hi, thanks for reporting.

> Quick survey on embulk input plugins told me there's no such option on existings

I think so. I had never seen plugin which has such option.

I've heard same request at different plugin.
https://github.com/embulk/embulk-input-sftp/issues/34

Personally, I think it's better that Embulk core have such feature if there're many requests of that feature.
Then, all Input/FileInput plugin will be able to act as same.

I suggest that you send a request to Embulk core.
Actually, I'm also in the Embulk organization group. Such feature request is helpful to consider future enhancement.

**Comment by hirosassa** [comment]
Thanks for rapid and kind response.
> Personally, I think it's better that Embulk core have such feature if there're many requests of that feature.
> Then, all Input/FileInput plugin will be able to act as same.
It's true.

I'll send a request to Embulk core.
Thank you for your suggestion!
